#
# Module manifest for module 'ConfluenceTool'
#
# Generated by: Confluence Export-Import Tool Team
#
# Generated on: $(Get-Date)
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ConfluenceTool.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '12345678-1234-1234-1234-123456789012'

# Author of this module
Author = 'Confluence Export-Import Tool Team'

# Company or vendor of this module
CompanyName = 'Open Source'

# Copyright statement for this module
Copyright = '(c) 2024 Confluence Export-Import Tool Team. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for exporting and importing Confluence spaces with multi-environment support. Cross-platform compatible with Windows and macOS using stable PowerShell versions.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Connect-ConfluenceAPI',
    'Get-ConfluenceSpaces', 
    'Export-ConfluenceSpace',
    'Import-ConfluenceSpace',
    'Sync-ConfluenceSpaces',
    'Compare-ConfluenceSpaces',
    'New-ConfluenceConfig',
    'Test-ConfluenceConfig',
    'Get-ConfluencePages',
    'Get-ConfluencePageContent',
    'Show-ConfluenceHelp'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Confluence', 'Export', 'Import', 'API', 'Migration', 'Backup', 'MultiEnvironment', 'CrossPlatform')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/distantsoil/Confluence-Export-Import-Tool/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/distantsoil/Confluence-Export-Import-Tool'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Experimental PowerShell version of the Confluence Export-Import Tool with cross-platform support.'

        # Prerelease string of this module
        Prerelease = 'experimental'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}